[package]
name = "rs-qq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
md5 = "0.7.0"
flate2 = { version = "1.0.17", features = ["rust_backend"], default-features = false }
prost = { version = "0.9.0", git = "https://github.com/lz1998/prost" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
futures = "0.3"
anyhow = "1"
tracing = "0.1"
lazy_static = "1.4.0"
async-trait = "0.1"
cached = "0.30.0"
rand = "0.8.4"
chrono = "0.4"
derivative = "2"
jcers = { version = "0.1.0", features = ["derive"] }
rq-engine = { path = "./rq-engine" }
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
    "local-time",
] }
[workspace]
members = []

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
incremental = false
codegen-units = 1
rpath = false
